# install: true
image:
  - Visual Studio 2015
  - Visual Studio 2017

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x64
      configuration: Release

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build: off
  # parallel: true

before_build:
  - cmd: cmake --version
  - cmd: git --version
  - cmd: set

build_script:
  - cmd: C:\Python36-x64\python.exe build.py
  - cmd: type build.ps1
  # - cmd: build.bat
  - ps: build.ps1

test_script:
  - cmd: exit 2
  # - cmd: cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
