#language: cpp

# install: true

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x64
      configuration: Release

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build:
  parallel: true
  project: demo.sln

before_build:
  - cmd: cmake --version
  - cmd: git --version
#build_script:
#  - cmd: cmake --version
